server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${GRAFANA_LOKI_URL}
    basic_auth:
      username: ${GRAFANA_LOKI_USER}
      password: ${GRAFANA_LOKI_TOKEN}

scrape_configs:
- job_name: car_scm_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: car_scm_pipeline
      env: dev
      __path__: /workspaces/scm-data-pipeline-v2/logs/*.log