CREATE OR REPLACE TABLE dim_product AS
    SELECT DISTINCT
        ProductID,
        CarMaker,
        CarModel,
        CASE 
            WHEN CarModel IN ('Catera', 'Galant', 'Malibu', '9-3', 'Stratus', '400SEL', '300D', 'Electra', 'J', 'Quattroporte', '9-5', 'Park Avenue', 'Mentor', 'Town Car', 'Sable', 'XJ Series', 'Cutlass Supreme', '57', '4000', 'Galaxie', 'Regal', 'LaCrosse', 'Dynasty', 'TL', '6000', 'Caprice', 'Maxima', 'Sonata', 'Jetta', 'Protege', 'Continental Flying Spur', 'Elantra', '525', 'S4', 'GS', 'STS', 'Millenia', 'Optima', '626', 'Forte', 'ES', 'G6', '760', 'Sebring', 'Intrepid', 'Accord', 'Cirrus', 'RL', '7 Series', 'Legacy', '9000', 'Lancer', 'G8', 'X-Type', 'DTS', 'A6', 'Neon', 'S-Type', 'C-Class', 'A8', 'Q', 'Kizashi', 'Taurus', 'W201', 'LTD Crown Victoria', 'IS', 'G37', 'S6', 'Grand Marquis', 'MKZ', 'E-Class', 'G35', 'S40', 'Continental', '400E', 'LeSabre', 'Camry', 'Imperial', 'Civic', 'Avalon', 'CC', 'Esteem', 'Lucerne', 'Roadmaster', '5000S', 'Reliant', 'Century', '300M', '57S', 'Corolla', '3 Series', '600SEL', '300', 'DeVille', 'LS', 'S80', 'A4', 'Genesis', 'Tempo', 'Grand Am', 'Passat', 'Citation', 'Somerset', '530', '5 Series', 'Lancer Evolution', 'S60', 'Reno', 'Sentra', '300SD', 'Cruze', 'Charger', 'Diamante', 'Phantom', 'Intrigue', 'Concorde', '100', '300SE', 'Bonneville', 'Daewoo Magnus', 'G25', 'Parisienne', 'G', '88', 'Seville', 'S-Class', 'Forenza', 'Sundance', 'Ciera', 'IS-F', 'Regency', 'Bel Air', 'Grand Prix', 'Aurora', 'Skylark', '745', 'M', 'Avenger') THEN 'Sedan'
            WHEN CarModel IN ('RX', 'Touareg 2', 'EX', 'Vitara', 'Pajero', 'Highlander Hybrid', 'Navigator', 'X5', 'Bravada', 'Mariner', 'Forester', 'Yukon XL 1500', 'Bronco II', 'X3', 'Borrego', 'Suburban', 'Durango', 'Bronco', 'VUE', 'Montero', 'Accord Crosstour', 'Trooper', 'Range Rover Classic', 'Acadia', 'Yukon XL 2500', 'Grand Vitara', 'Sidekick', 'CX-7', 'Samurai', 'X-90', 'Explorer Sport', 'Nitro', 'Sportage', 'Sequoia', 'Q7', 'Aviator', 'GL-Class', 'Equinox', 'Pacifica', 'XC70', 'SLX', 'Compass', 'Tucson', 'Yukon', 'Rainier', 'Suburban 2500', 'Defender', 'QX56', 'Tribeca', 'Taurus X', 'K5 Blazer', '9-7X', 'XC60', 'Pathfinder', 'Amigo', 'Grand Cherokee', 'Rogue', 'Rodeo', 'Tracker', 'LX', 'Escape', 'Suburban 1500', 'Murano', 'Wrangler', 'Veracruz', 'Escalade EXT', 'Flex', 'CR-V', 'Jimmy', '4Runner', 'CX-9', 'Tahoe', 'Sorento', 'Allroad', 'Escalade', 'Commander', 'Liberty', 'Pathfinder Armada', 'Venza', 'Endeavor', 'MDX', 'Freelander', 'M-Class', 'Range Rover Sport', 'QX', 'Land Cruiser', 'Navajo', 'Excursion', 'X6', 'Mountaineer', 'Highlander', 'Edge', 'XL-7', 'ZDX', 'RAV4', 'GX', 'Outback', 'Pilot', 'SJ', 'Explorer', 'Discovery', 'Range Rover', 'R-Class', 'VehiCROSS') THEN 'SUV / Crossover'
            WHEN CarModel IN ('Viper RT/10', 'XLR', 'CL-Class', 'Scirocco', 'XLR-V', 'Esprit', 'Cabriolet', 'Eclipse', 'GTO', 'Continental GT', 'F430', 'Mark VIII', 'S2000', 'Skyhawk', '599 GTB Fiorano', 'Coachbuilder', 'Tiburon', 'Talon', 'EXP', 'Cobalt SS', 'Eldorado', 'MR2', 'C70', 'Eos', 'NSX', 'Z4 M', 'riolet', 'Gallardo', 'Viper', 'Laser', '612 Scaglietti', '370Z', 'MGB', 'SL-Class', 'SLK-Class', 'M Roadster', 'Spyder', '928', 'XK', 'Solara', 'A5', 'Murciélago', 'Sunbird', 'Camaro', '458 Italia', 'CLK-Class', 'SLS-Class', 'Daytona', 'LeMans', 'Continental Mark VII', 'Beretta', 'Mustang', 'M6', 'Challenger', '944', 'Murciélago LP640', 'Sunfire', 'Vega', 'Diablo', 'CR-X', '300SL', 'S5', 'CTS-V', 'Aero 8', 'Monte Carlo', 'Integra', 'Civic Si', 'Z3', '240SX', 'Fiero', 'RS 4', 'GT-R', 'V12 Vantage', 'Azure', 'Crossfire Roadster', 'Capri', 'NX', '900', 'Corvette', 'TT', '280ZX', 'Corrado', 'M5', 'FCX Clarity', 'Prowler', 'Vantage', 'Firebird', 'Boxster', 'Riviera', 'Celica', 'XT', 'GranTurismo', 'Cougar', 'CLS-Class', '430', 'Elise', 'Paseo', 'M3', 'XK Series', 'Vision', 'MX-5', '911', 'Alcyone SVX', 'MX-3', 'MX-6', 'California', 'Continental GTC', 'Starion', 'Gran Sport') THEN 'Coupe / Sport / Convertible'
            WHEN CarModel IN ('Sierra 2500HD', 'Tacoma Xtra', 'F-Series', 'Ram 3500', 'Mighty Max', 'Titan', 'Ridgeline', 'Tundra', '2500 Club Coupe', '3500', 'B-Series Plus', 'Sierra 3500HD', 'Silverado 3500HD', 'Canyon', '1500', 'Mighty Max Macro', 'Sierra 3500', 'T100', 'Frontier', 'Ram 2500', 'F350', 'Comanche', 'F450', 'Raider', 'Hombre Space', 'Ranger', 'Tacoma', 'Silverado 1500', 'Baja', 'Sierra 1500', 'F150', 'Ram 1500', 'Hombre', 'B-Series', '2500', 'i-370', '3500 Club Coupe', 'Explorer Sport Trac', 'Ram 1500 Club', 'Dakota', 'Silverado 2500', 'Avalanche 2500', 'B2000', 'F-Series Super Duty', 'Avalanche', 'Truck') THEN 'Pickup Trucks'
            WHEN CarModel IN ('Trans Sport', 'Freestar', 'Express', 'APV', 'Sedona', 'Ram Wagon B150', 'Club Wagon', 'Terraza', 'Montana', 'Aerostar', 'Type 2', 'Grand Voyager', 'Previa', 'E150', 'Silhouette', 'Quest', 'Odyssey', 'Ram Van 1500', 'Ram Van 3500', 'L300', 'Sportvan G10', 'Astro', 'Windstar', 'Sprinter', 'Voyager', 'Monterey', 'Ram Van 2500', 'Express 3500', 'Oasis', 'MPV', 'Safari', 'Savana 1500', 'Econoline E350', 'Express 2500', 'Rally Wagon 1500', 'Rondo', 'Sportvan G30', 'Eurovan', 'Express 1500', 'E250', 'G-Series G10', 'Colt Vista', 'Econoline E250', 'Savana 3500', 'Town & Country') THEN 'Minivan / Van'
            WHEN CarModel IN ('CX', 'Soul', 'GTI', 'Rabbit', 'New Beetle', 'Loyale', '1000', 'CT', 'Mazdaspeed 3', 'Metro', 'Cooper Countryman', 'Swift', 'Focus', 'Gemini', 'Matrix', 'Familia', 'V40', 'V50', 'Aveo', 'Cutlass Cruiser', 'V90', '850', 'Vibe', 'Cube', 'Justy', 'xB', 'Caliber', 'A3', 'Excel', 'Aspire', 'Impreza WRX', 'HHR', 'Mini Cooper', 'xD', 'Countryman', 'Mirage', 'Lanos', 'C30', 'rio', 'Precis', 'iQ', 'Firefly', 'Beetle', 'Lynx', 'Impreza', 'Golf', 'Festiva') THEN 'Hatchback / Station Wagon'
            
            ELSE 'Other'
        END AS CarType,
        CarColor,
        CASE
            WHEN CarColor IN ('Red', 'Crimson', 'Maroon', 'Pink', 'Fuchsia') THEN 'Red & Pink'
            WHEN CarColor IN ('Purple', 'Violet', 'Indigo', 'Mauve', 'Puce') THEN 'Purple'
            WHEN CarColor IN ('Blue', 'Teal', 'Turquoise', 'Aquamarine') THEN 'Blue & Teal'
            WHEN CarColor = 'Green' THEN 'Green'
            WHEN CarColor IN ('Yellow', 'Orange', 'Goldenrod') THEN 'Yellow & Orange'
            WHEN CarColor = 'Khaki' THEN 'Earth Tones'
            
            ELSE 'Other'
        END AS CarColorGroup,
        CarModelYear,
        CarPrice
    FROM staging_raw;